controllers:
    resource: ../src/Infrastructure/Symfony/Controller/
    type: annotation

kernel:
    resource: ../src/Infrastructure/Symfony/Kernel.php
    type: annotation

app_directory:
    # loads routes from the YAML, XML or PHP files found in that directory
    resource: 'routes/app'
    type:     directory
